version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_USER=admin
      - POSTGRES_DB=college_db
